### ISSUE TITLE
Issue when formatting scenario outline examples

### ISSUE THREAD

**Issue by tifabien** [malukenho/kawaii-gherkin#3]
Hi and thanks for your project which seems to be promising !

I started to play with it and faced to my first issue when I don't have any feature description line and also on the alignment of scenario outline examples.

If you take a look at my feature 

```
Feature: Test Welcome page

    Scenario Outline:
        When I navigate in <locale> language
        Then I should see "<message>"

        Examples:
            | locale | message                           |
            | fr     | Bienvenue %USERNAME%.             |
            | de     | Herzlich Willkommen %USERNAME%.   |
            | ar     | مرحبا %USERNAME%                  |
            | ja     | ようこそ %USERNAME%                |
```

When I apply a check or fix command it formats the feature like the following : 

```
Feature: Test Welcome page


    Scenario Outline:
        When I navigate in <locale> language
        Then I should see "<message>"

        Examples:
          | locale | message                         |
| fr     | Bienvenue %USERNAME%.           |
| de     | Herzlich Willkommen %USERNAME%. |
| ar     | مرحبا %USERNAME%                |
| ja     | ようこそ %USERNAME%                 |
```

As you can see, it created 2 extra empty lines between Feature and Scenario Outline sections, and failed on example lines.

I'm using Windows, don't know if it could be related.

Thanks for your help !

**Comment by malukenho** [comment]
@tifabien are you using windows new line char at the end of lines?

**Comment by tifabien** [comment]
I'm using \n (LF) chars indeed. Could it be problem?

**Comment by malukenho** [comment]
@tifabien no. I was not be able to reproduce the problem here coping and pasting the code above. Could you send me the file in attach?

**Comment by tifabien** [comment]
I'm not able to send you the file right now but will send you monday morning.
Btw, I ran also your unit tests which failed too. Weird as they passed with Travis...

**Comment by malukenho** [comment]
@tifabien weird indeed. please, send me more information about your environment and the file on Monday.

**Comment by tifabien** [comment]
Hi @malukenho 
As promise you'll find attached my feature file (I renamed the file into .txt extension as .feature is not supported by GH)
[welcome.txt](https://github.com/malukenho/kawaii-gherkin/files/182019/welcome.txt)

Think the error could be on PHP_EOL chars as my feature has LF chars (to be consistent with my project) but PHP_EOL is CRLF in Windows.

**Comment by malukenho** [comment]
@tifabien could you please check on `dev-master` if everything is OK?

**Comment by tifabien** [comment]
@malukenho I tested on dev-master and it works like a charm :+1: Thanks very much !

Btw I got a question regarding the 2 empty lines between Feature and Scenario sections. Shouldn't we have only one empty line?

**Comment by malukenho** [comment]
@tifabien actually it's expecting only one line (at least for me), look at https://github.com/malukenho/kawaii-gherkin/blob/master/tests/functional/check-file-can-format-table-using-unix-line-endings.phpt#L26

**Comment by tifabien** [comment]
@malukenho I tested on both Windows and Mac and fix command adds 2 empty lines between Feature and Scenario sections. Think you should only have one empty line between the two section.

Is it voluntary you did not add the Feature section in your [https://github.com/malukenho/kawaii-gherkin/blob/master/tests/functional/check-file-can-format-table-using-unix-line-endings.phpt](https://github.com/malukenho/kawaii-gherkin/blob/master/tests/functional/check-file-can-format-table-using-unix-line-endings.phpt) test file?

**Comment by malukenho** [comment]
Well, the `Feature` session is not showed up in the diff when you run the check command, I'll testing the diff output on console.

Sorry for the lack of time, I'll fix it during the day.

**Comment by tifabien** [comment]
@malukenho I just checked your fix and it seems working well !
Thanks a lot !

**Comment by malukenho** [comment]
@tifabien nice \o/

I'll tag kawaii-gherkin by tomorrow, so you can use the new version. Thank you by report the bug :dancer:
