### ISSUE TITLE
Get parser by a file

### ISSUE THREAD

**Issue by jackmakiyama** [malukenho/kawaii-gherkin#8]
The file `./bin/kawaii` have a comment recommending move the parse to a file:

``` php
// TODO: get this parser by a file
$keywords = new Behat\Gherkin\Keywords\ArrayKeywords([
    'en' => [
        'feature'          => 'Feature',
        'background'       => 'Background',
        'scenario'         => 'Scenario',
        'scenario_outline' => 'Scenario Outline|Scenario Template',
        'examples'         => 'Examples|Scenarios',
        'given'            => 'Given',
        'when'             => 'When',
        'then'             => 'Then',
        'and'              => 'And',
        'but'              => 'But',
    ],
]);

$lexer  = new Behat\Gherkin\Lexer($keywords);
$parser = new Behat\Gherkin\Parser($lexer);
```

I removed this comment in PR #7.

**Comment by malukenho** [comment]
You can get a complete file with languages above`vendor/behat/gherkin/i18n.php` directory. We can load that and just let the user configure the `language` that they want to use. Default `english`.

Something like it:

``` php
$keywords = new Behat\Gherkin\Keywords\ArrayKeywords(
    require __DIR__ . '/../vendor/behat/gherkin/i18n.php'
);
```

also needs **functional** and **unit** testing for `--language=en` parameter, and documment it.

@jackmakiyama

**Comment by jackmakiyama** [comment]
@malukenho we dont need an attribute `--language` the Gherkin uses the tag `# language: fr` on head of feature file to work with others languages.
